Trip = (title, description, user, businesses) ->
  @title = title
  @description = description
  @user = user
  @businesses = businesses
  return

TripUser = (slug, first_name, last_name) ->
  @slug = slug
  @first_name = first_name
  @last_name = last_name
  return

$ ->
  slug = undefined
  username = undefined
  slug = $('.tripShowInfo').data('id')
  username = $('.tripShowInfo').data('name')
  $.getJSON '/u/' + username + '/travelstories/' + slug + '.json', (data) ->
    biz = undefined
    i = undefined
    trip = undefined
    tripText = undefined
    user = undefined
    trip = new Trip(data.trip.title, data.trip.description, data.trip.user, data.trip.businesses)
    biz = trip.businesses
    user = new TripUser(trip.user.slug, trip.user.first_name, trip.user.last_name)
    tripText = '<h2>' + trip.title + '</h2>'
    tripText += '<p>by <a href=\'/u/' + username + '\'>' + user.fullName() + '</a></p>'
    tripText += '<p>' + trip.description + '</p>'
    tripText += '<hr><h4>Places I visited</h4>'
    tripText += '<ul>'
    i = 0
    while i < biz.length
      tripText += '<li>' + biz[i].name + '</li>'
      i++
    tripText += '</ul>'
    $('.tripShowInfo').append tripText
  return

TripUser::fullName = ->
  @first_name + ' ' + @last_name

# ---
# generated by js2coffee 2.2.0
