# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$ ->
  $("#addNewChoice").on "click", ->
    $("#biz_choices").append($("#new_choice_form").html())

@removeChoice = (element) ->
  element.parent().remove()

# ---
# generated by js2coffee 2.2.0
